# Core Configuration
owner: hirempire
repo: status

# Monitoring Targets
sites:
  - name: Database
    url: https://data.hirempire.com/health
  - name: API
    url: https://api.hirempire.com
  - name: Forward Email (IPv6)
    url: forwardemail.net
    port: 80
    check: "tcp-ping"
    ipv6: true

# Status Website Customization
status-website:
  # If using a custom domain (e.g., status.hirempire.com), uncomment the 'cname' line below:
  cname: status.hirempire.com
  
  # Default GitHub Pages URL: /status
  baseUrl: /status
  
  logoUrl: https://assets-hirempire.s3.us-east-1.amazonaws.com/hirempire-logo-blue.svg
  name: Hirempire Status
  introTitle: "**Hirempire** Service Status"
  introMessage: This page monitors the real-time health of our database, API, and core infrastructure. Powered by GitHub Actions.
  
navbar:
    - title: Status
      href: /status
    - title: Main Site
      href: https://hirempire.com
    - title: Support
      href: mailto:support@hirempire.com
    - title: GitHub
      href: https://github.com/hirempire/status
